// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Task struct {
	ID     int32
	UserID int32
	Title  string
	Done   sql.NullBool
}

type User struct {
	ID   int32
	Name string
}
